### PR TITLE
Add inverse/inverted style

### PR DESCRIPTION
**Pull request by toothbrush7777777**

### CODE REVIEW

**Comment by spenserblack** [comment]
Thanks for this!
Since you have contributed quite a bit, would you like to be added to the authors list in `Cargo.toml`?
I could also make you a collaborator and co-owner if you're interested in maintaining this crate.

**Comment by toothbrush7777777** [comment]
> 
> 
> Thanks for this!
> Since you have contributed quite a bit, would you like to be added to the authors list in `Cargo.toml`?
> I could also make you a collaborator and co-owner if you're interested in maintaining this crate.

Yes,

**Comment by toothbrush7777777** [comment]
> 
> 
> Thanks for this!
> Since you have contributed quite a bit, would you like to be added to the authors list in `Cargo.toml`?
> I could also make you a collaborator and co-owner if you're interested in maintaining this crate.

I seem to have missed this message.
Yes, I don't mind maintaining the crate.

**Comment by spenserblack** [comment]
Great, thanks for your help!
I invited you to be a collaborator. You should be able to add yourself to the authors list in `Cargo.toml` if you accept the invitation.
If you have a crates.io account, I can also make you a co-owner so that you can publish new versions.

**Comment by toothbrush7777777** [comment]
> 
> 
> If you have a crates.io account, I can also make you a co-owner so that you can publish new versions.

I have a crates.io account now.

**Comment by spenserblack** [comment]
Awesome! Invite sent.
Please let me know if you have any questions about publishing new releases.

**Pull request merged**
