### PR TITLE
Add warning compile- vs run-time styling

### PR DESCRIPTION
**Pull request by spenserblack**

### CODE REVIEW

**Comment by spenserblack** [comment]
@toothbrush7777777 Checking since this repo hasn't had activity in a long time: are you still interested in maintaining this project?

I was thinking of releasing a new patch version with this warning and the updated `syn` dependency.

**Comment by toothbrush7777777** [comment]
@spenserblack Yes, though there hasn't really been anything to do.

I'm not sure what you mean by the warning, though. Any terminal which supports ANSI colour escape codes will interpret the compiled string correctly.

**Comment by spenserblack** [comment]
>I'm not sure what you mean by the warning, though.

Since they're set at compile-time, the ANSI escape codes are baked into the string, which harms portability. For example, if you compiled an executable on your system and distributed it somewhere else, this library wouldn't be able to take advantage of `NOCOLOR=true`. You'd have to manually choose when to render colored vs uncolored strings, instead of leaving it up to this library.

Off the top of my head, here are some reasons why you would want to disable coloring:
- The user is redirecting output, e.g. `my-executable > out`.
- The user may want to disable coloring if they have a visual impairment which makes colored output hard to read. Or it could clash with their terminal theme, or they might simply prefer a simpler output.
- A user's terminal *doesn't* support ANSI colors, if you're looking to make your executable compatible with as many environments as possible.

**Comment by toothbrush7777777** [comment]
@spenserblack Right, that's what I thought you meant. Perhaps you could incorporate some of that into the warning message to be as clear as possible?

**Pull request merged**
